apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: db-agent-pdb
  namespace: db-agent
  labels:
    app: db-agent
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: db-agent
