// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: proto/dbagent/agent.proto

package dbagent

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	StatusCode_SUCCESS           StatusCode = 0
	StatusCode_ERROR             StatusCode = 1
	StatusCode_AUTH_FAILED       StatusCode = 2
	StatusCode_DRIFT_DETECTED    StatusCode = 3
	StatusCode_VALIDATION_FAILED StatusCode = 4
	StatusCode_EXECUTION_FAILED  StatusCode = 5
	StatusCode_NOT_FOUND         StatusCode = 6
	StatusCode_PERMISSION_DENIED StatusCode = 7
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "SUCCESS",
		1: "ERROR",
		2: "AUTH_FAILED",
		3: "DRIFT_DETECTED",
		4: "VALIDATION_FAILED",
		5: "EXECUTION_FAILED",
		6: "NOT_FOUND",
		7: "PERMISSION_DENIED",
	}
	StatusCode_value = map[string]int32{
		"SUCCESS":           0,
		"ERROR":             1,
		"AUTH_FAILED":       2,
		"DRIFT_DETECTED":    3,
		"VALIDATION_FAILED": 4,
		"EXECUTION_FAILED":  5,
		"NOT_FOUND":         6,
		"PERMISSION_DENIED": 7,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dbagent_agent_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_proto_dbagent_agent_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_dbagent_agent_proto_rawDescGZIP(), []int{0}
}

// Request/Response Messages
type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientVersion string `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dbagent_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbagent_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_dbagent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentVersion string `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Status       string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp    int64  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dbagent_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbagent_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_dbagent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type CompareManifestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DatabaseName    string    `protobuf:"bytes,1,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	Manifest        *Manifest `protobuf:"bytes,2,opt,name=manifest,proto3" json:"manifest,omitempty"`
	IncludeDataDiff bool      `protobuf:"varint,3,opt,name=include_data_diff,json=includeDataDiff,proto3" json:"include_data_diff,omitempty"`
}

func (x *CompareManifestRequest) Reset() {
	*x = CompareManifestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dbagent_agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompareManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareManifestRequest) ProtoMessage() {}

func (x *CompareManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbagent_agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareManifestRequest.ProtoReflect.Descriptor instead.
func (*CompareManifestRequest) Descriptor() ([]byte, []int) {
	return file_proto_dbagent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *CompareManifestRequest) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *CompareManifestRequest) GetManifest() *Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *CompareManifestRequest) GetIncludeDataDiff() bool {
	if x != nil {
		return x.IncludeDataDiff
	}
	return false
}

type CompareManifestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsIdentical     bool        `protobuf:"varint,1,opt,name=is_identical,json=isIdentical,proto3" json:"is_identical,omitempty"`
	Differences     []string    `protobuf:"bytes,2,rep,name=differences,proto3" json:"differences,omitempty"`
	MissingObjects  []string    `protobuf:"bytes,3,rep,name=missing_objects,json=missingObjects,proto3" json:"missing_objects,omitempty"`
	ExtraObjects    []string    `protobuf:"bytes,4,rep,name=extra_objects,json=extraObjects,proto3" json:"extra_objects,omitempty"`
	DataDifferences []*DataDiff `protobuf:"bytes,5,rep,name=data_differences,json=dataDifferences,proto3" json:"data_differences,omitempty"`
	LocalChecksum   string      `protobuf:"bytes,6,opt,name=local_checksum,json=localChecksum,proto3" json:"local_checksum,omitempty"`
	RemoteChecksum  string      `protobuf:"bytes,7,opt,name=remote_checksum,json=remoteChecksum,proto3" json:"remote_checksum,omitempty"`
}

func (x *CompareManifestResponse) Reset() {
	*x = CompareManifestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dbagent_agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompareManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareManifestResponse) ProtoMessage() {}

func (x *CompareManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbagent_agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareManifestResponse.ProtoReflect.Descriptor instead.
func (*CompareManifestResponse) Descriptor() ([]byte, []int) {
	return file_proto_dbagent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *CompareManifestResponse) GetIsIdentical() bool {
	if x != nil {
		return x.IsIdentical
	}
	return false
}

func (x *CompareManifestResponse) GetDifferences() []string {
	if x != nil {
		return x.Differences
	}
	return nil
}

func (x *CompareManifestResponse) GetMissingObjects() []string {
	if x != nil {
		return x.MissingObjects
	}
	return nil
}

func (x *CompareManifestResponse) GetExtraObjects() []string {
	if x != nil {
		return x.ExtraObjects
	}
	return nil
}

func (x *CompareManifestResponse) GetDataDifferences() []*DataDiff {
	if x != nil {
		return x.DataDifferences
	}
	return nil
}

func (x *CompareManifestResponse) GetLocalChecksum() string {
	if x != nil {
		return x.LocalChecksum
	}
	return ""
}

func (x *CompareManifestResponse) GetRemoteChecksum() string {
	if x != nil {
		return x.RemoteChecksum
	}
	return ""
}

// Core Data Types
type Manifest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version     string            `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Description string            `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Author      string            `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	CreatedAt   int64             `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Migrations  []*Migration      `protobuf:"bytes,5,rep,name=migrations,proto3" json:"migrations,omitempty"`
	SeedData    []*SeedData       `protobuf:"bytes,6,rep,name=seed_data,json=seedData,proto3" json:"seed_data,omitempty"`
	Metadata    *ManifestMetadata `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dbagent_agent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbagent_agent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_proto_dbagent_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Manifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Manifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Manifest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Manifest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Manifest) GetMigrations() []*Migration {
	if x != nil {
		return x.Migrations
	}
	return nil
}

func (x *Manifest) GetSeedData() []*SeedData {
	if x != nil {
		return x.SeedData
	}
	return nil
}

func (x *Manifest) GetMetadata() *ManifestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Migration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version         string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Name            string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UpSql           string   `protobuf:"bytes,4,opt,name=up_sql,json=upSql,proto3" json:"up_sql,omitempty"`
	DownSql         string   `protobuf:"bytes,5,opt,name=down_sql,json=downSql,proto3" json:"down_sql,omitempty"`
	Dependencies    []string `protobuf:"bytes,6,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	Checksum        string   `protobuf:"bytes,7,opt,name=checksum,proto3" json:"checksum,omitempty"`
	ExecutionTimeMs int64    `protobuf:"varint,8,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
}

func (x *Migration) Reset() {
	*x = Migration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dbagent_agent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Migration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration) ProtoMessage() {}

func (x *Migration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbagent_agent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration.ProtoReflect.Descriptor instead.
func (*Migration) Descriptor() ([]byte, []int) {
	return file_proto_dbagent_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Migration) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Migration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Migration) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Migration) GetUpSql() string {
	if x != nil {
		return x.UpSql
	}
	return ""
}

func (x *Migration) GetDownSql() string {
	if x != nil {
		return x.DownSql
	}
	return ""
}

func (x *Migration) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *Migration) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *Migration) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

type DataDiff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName   string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Operation   string `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	RecordCount int32  `protobuf:"varint,3,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *DataDiff) Reset() {
	*x = DataDiff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dbagent_agent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDiff) ProtoMessage() {}

func (x *DataDiff) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbagent_agent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDiff.ProtoReflect.Descriptor instead.
func (*DataDiff) Descriptor() ([]byte, []int) {
	return file_proto_dbagent_agent_proto_rawDescGZIP(), []int{6}
}

func (x *DataDiff) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *DataDiff) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *DataDiff) GetRecordCount() int32 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *DataDiff) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SeedData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Environment   string   `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	TableName     string   `protobuf:"bytes,2,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	SqlStatements []string `protobuf:"bytes,3,rep,name=sql_statements,json=sqlStatements,proto3" json:"sql_statements,omitempty"`
	Checksum      string   `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
}

func (x *SeedData) Reset() {
	*x = SeedData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dbagent_agent_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedData) ProtoMessage() {}

func (x *SeedData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbagent_agent_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedData.ProtoReflect.Descriptor instead.
func (*SeedData) Descriptor() ([]byte, []int) {
	return file_proto_dbagent_agent_proto_rawDescGZIP(), []int{7}
}

func (x *SeedData) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *SeedData) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *SeedData) GetSqlStatements() []string {
	if x != nil {
		return x.SqlStatements
	}
	return nil
}

func (x *SeedData) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type ManifestMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinRuntimeVersion string            `protobuf:"bytes,1,opt,name=min_runtime_version,json=minRuntimeVersion,proto3" json:"min_runtime_version,omitempty"`
	MaxRuntimeVersion string            `protobuf:"bytes,2,opt,name=max_runtime_version,json=maxRuntimeVersion,proto3" json:"max_runtime_version,omitempty"`
	Tags              []string          `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	CustomProperties  map[string]string `protobuf:"bytes,4,rep,name=custom_properties,json=customProperties,proto3" json:"custom_properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ManifestMetadata) Reset() {
	*x = ManifestMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dbagent_agent_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManifestMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestMetadata) ProtoMessage() {}

func (x *ManifestMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbagent_agent_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestMetadata.ProtoReflect.Descriptor instead.
func (*ManifestMetadata) Descriptor() ([]byte, []int) {
	return file_proto_dbagent_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ManifestMetadata) GetMinRuntimeVersion() string {
	if x != nil {
		return x.MinRuntimeVersion
	}
	return ""
}

func (x *ManifestMetadata) GetMaxRuntimeVersion() string {
	if x != nil {
		return x.MaxRuntimeVersion
	}
	return ""
}

func (x *ManifestMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ManifestMetadata) GetCustomProperties() map[string]string {
	if x != nil {
		return x.CustomProperties
	}
	return nil
}

// Additional request/response types would go here...
// For brevity, I'm including the core types that are most essential

var File_proto_dbagent_agent_proto protoreflect.FileDescriptor

var file_proto_dbagent_agent_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x62, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x64, 0x62, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_dbagent_agent_proto_rawDescOnce sync.Once
	file_proto_dbagent_agent_proto_rawDescData = file_proto_dbagent_agent_proto_rawDesc
)

func file_proto_dbagent_agent_proto_rawDescGZIP() []byte {
	file_proto_dbagent_agent_proto_rawDescOnce.Do(func() {
		file_proto_dbagent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_dbagent_agent_proto_rawDescData)
	})
	return file_proto_dbagent_agent_proto_rawDescData
}

var file_proto_dbagent_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_dbagent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_dbagent_agent_proto_goTypes = []interface{}{
	(StatusCode)(0),                   // 0: dbagent.StatusCode
	(*PingRequest)(nil),               // 1: dbagent.PingRequest
	(*PingResponse)(nil),              // 2: dbagent.PingResponse
	(*CompareManifestRequest)(nil),    // 3: dbagent.CompareManifestRequest
	(*CompareManifestResponse)(nil),   // 4: dbagent.CompareManifestResponse
	(*Manifest)(nil),                  // 5: dbagent.Manifest
	(*Migration)(nil),                 // 6: dbagent.Migration
	(*DataDiff)(nil),                  // 7: dbagent.DataDiff
	(*SeedData)(nil),                  // 8: dbagent.SeedData
	(*ManifestMetadata)(nil),          // 9: dbagent.ManifestMetadata
	(*DownloadManifestRequest)(nil),   // 10: dbagent.DownloadManifestRequest
	(*DownloadManifestResponse)(nil),  // 11: dbagent.DownloadManifestResponse
	(*DeployManifestRequest)(nil),     // 12: dbagent.DeployManifestRequest
	(*DeployManifestResponse)(nil),    // 13: dbagent.DeployManifestResponse
	(*DeploymentHistoryRequest)(nil),  // 14: dbagent.DeploymentHistoryRequest
	(*DeploymentHistoryResponse)(nil), // 15: dbagent.DeploymentHistoryResponse
	(*BootstrapRequest)(nil),          // 16: dbagent.BootstrapRequest
	(*BootstrapResponse)(nil),         // 17: dbagent.BootstrapResponse
	(*DeploymentVersion)(nil),         // 18: dbagent.DeploymentVersion
	(*MigrationResult)(nil),           // 19: dbagent.MigrationResult
}
var file_proto_dbagent_agent_proto_depIdxs = []int32{
	5, // 0: dbagent.CompareManifestRequest.manifest:type_name -> dbagent.Manifest
	7, // 1: dbagent.CompareManifestResponse.data_differences:type_name -> dbagent.DataDiff
	6, // 2: dbagent.Manifest.migrations:type_name -> dbagent.Migration
	8, // 3: dbagent.Manifest.seed_data:type_name -> dbagent.SeedData
	9, // 4: dbagent.Manifest.metadata:type_name -> dbagent.ManifestMetadata
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_proto_dbagent_agent_proto_init() }
func file_proto_dbagent_agent_proto_init() {
	if File_proto_dbagent_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_dbagent_agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dbagent_agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dbagent_agent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompareManifestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dbagent_agent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompareManifestResponse); i {
			case 0:
				return &v.sizeCache
			case 1:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dbagent_agent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Manifest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dbagent_agent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Migration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dbagent_agent_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataDiff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dbagent_agent_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeedData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dbagent_agent_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManifestMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_dbagent_agent_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dbagent_agent_proto_goTypes,
		DependencyIndexes: file_proto_dbagent_agent_proto_depIdxs,
		EnumInfos:         file_proto_dbagent_agent_proto_enumTypes,
		MessageInfos:      file_proto_dbagent_agent_proto_msgTypes,
	}.Build()
	File_proto_dbagent_agent_proto = out.File
	file_proto_dbagent_agent_proto_rawDesc = nil
	file_proto_dbagent_agent_proto_goTypes = nil
}

// Additional message types
type DownloadManifestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DatabaseName string `protobuf:"bytes,1,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	IncludeData  bool   `protobuf:"varint,2,opt,name=include_data,json=includeData,proto3" json:"include_data,omitempty"`
	Environment  string `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
}

func (x *DownloadManifestRequest) Reset() {
	*x = DownloadManifestRequest{}
}

func (x *DownloadManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadManifestRequest) ProtoMessage() {}

func (x *DownloadManifestRequest) ProtoReflect() protoreflect.Message {
	return nil
}

type DownloadManifestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Manifest     *Manifest `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Checksum     string    `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	ObjectsCount int32     `protobuf:"varint,3,opt,name=objects_count,json=objectsCount,proto3" json:"objects_count,omitempty"`
}

func (x *DownloadManifestResponse) Reset() {
	*x = DownloadManifestResponse{}
}

func (x *DownloadManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadManifestResponse) ProtoMessage() {}

func (x *DownloadManifestResponse) ProtoReflect() protoreflect.Message {
	return nil
}

type DeployManifestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DatabaseName  string    `protobuf:"bytes,1,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	Manifest      *Manifest `protobuf:"bytes,2,opt,name=manifest,proto3" json:"manifest,omitempty"`
	DryRun        bool      `protobuf:"varint,3,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	TargetVersion string    `protobuf:"bytes,4,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	Force         bool      `protobuf:"varint,5,opt,name=force,proto3" json:"force,omitempty"`
}

func (x *DeployManifestRequest) Reset() {
	*x = DeployManifestRequest{}
}

func (x *DeployManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployManifestRequest) ProtoMessage() {}

func (x *DeployManifestRequest) ProtoReflect() protoreflect.Message {
	return nil
}

type DeployManifestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success         bool               `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Status          string             `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Migrations      []*MigrationResult `protobuf:"bytes,3,rep,name=migrations,proto3" json:"migrations,omitempty"`
	ExecutionPlan   string             `protobuf:"bytes,4,opt,name=execution_plan,json=executionPlan,proto3" json:"execution_plan,omitempty"`
	ExecutionTimeMs int64              `protobuf:"varint,5,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	Warnings        []string           `protobuf:"bytes,6,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Errors          []string           `protobuf:"bytes,7,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *DeployManifestResponse) Reset() {
	*x = DeployManifestResponse{}
}

func (x *DeployManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployManifestResponse) ProtoMessage() {}

func (x *DeployManifestResponse) ProtoReflect() protoreflect.Message {
	return nil
}

type DeploymentHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DatabaseName string `protobuf:"bytes,1,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	Limit        int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset       int32  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *DeploymentHistoryRequest) Reset() {
	*x = DeploymentHistoryRequest{}
}

func (x *DeploymentHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentHistoryRequest) ProtoMessage() {}

func (x *DeploymentHistoryRequest) ProtoReflect() protoreflect.Message {
	return nil
}

type DeploymentHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deployments []*DeploymentVersion `protobuf:"bytes,1,rep,name=deployments,proto3" json:"deployments,omitempty"`
	TotalCount  int32                `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	HasMore     bool                 `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
}

func (x *DeploymentHistoryResponse) Reset() {
	*x = DeploymentHistoryResponse{}
}

func (x *DeploymentHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentHistoryResponse) ProtoMessage() {}

func (x *DeploymentHistoryResponse) ProtoReflect() protoreflect.Message {
	return nil
}

type BootstrapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DatabaseName     string    `protobuf:"bytes,1,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	ConnectionString string    `protobuf:"bytes,2,opt,name=connection_string,json=connectionString,proto3" json:"connection_string,omitempty"`
	Manifest         *Manifest `protobuf:"bytes,3,opt,name=manifest,proto3" json:"manifest,omitempty"`
	CreateDatabase   bool      `protobuf:"varint,4,opt,name=create_database,json=createDatabase,proto3" json:"create_database,omitempty"`
}

func (x *BootstrapRequest) Reset() {
	*x = BootstrapRequest{}
}

func (x *BootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapRequest) ProtoMessage() {}

func (x *BootstrapRequest) ProtoReflect() protoreflect.Message {
	return nil
}

type BootstrapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success         bool               `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DatabaseName    string             `protobuf:"bytes,2,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	Migrations      []*MigrationResult `protobuf:"bytes,3,rep,name=migrations,proto3" json:"migrations,omitempty"`
	ExecutionTimeMs int64              `protobuf:"varint,4,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	Warnings        []string           `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Errors          []string           `protobuf:"bytes,6,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *BootstrapResponse) Reset() {
	*x = BootstrapResponse{}
}

func (x *BootstrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapResponse) ProtoMessage() {}

func (x *BootstrapResponse) ProtoReflect() protoreflect.Message {
	return nil
}

type DeploymentVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DatabaseName    string             `protobuf:"bytes,2,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	Version         string             `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Status          string             `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	AppliedAt       int64              `protobuf:"varint,5,opt,name=applied_at,json=appliedAt,proto3" json:"applied_at,omitempty"`
	AppliedBy       string             `protobuf:"bytes,6,opt,name=applied_by,json=appliedBy,proto3" json:"applied_by,omitempty"`
	Checksum        string             `protobuf:"bytes,7,opt,name=checksum,proto3" json:"checksum,omitempty"`
	ExecutionTimeMs int64              `protobuf:"varint,8,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	Migrations      []*MigrationResult `protobuf:"bytes,9,rep,name=migrations,proto3" json:"migrations,omitempty"`
}

func (x *DeploymentVersion) Reset() {
	*x = DeploymentVersion{}
}

func (x *DeploymentVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentVersion) ProtoMessage() {}

func (x *DeploymentVersion) ProtoReflect() protoreflect.Message {
	return nil
}

type MigrationResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version         string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Name            string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status          string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ExecutionTimeMs int64  `protobuf:"varint,4,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	ErrorMessage    string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Checksum        string `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
}

func (x *MigrationResult) Reset() {
	*x = MigrationResult{}
}

func (x *MigrationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationResult) ProtoMessage() {}

func (x *MigrationResult) ProtoReflect() protoreflect.Message {
	return nil
}
